#spring:
  #application:
    #name: CONFIG-DEV
#eureka:
  #instance:
    #prefer-ip-address: true
  #client:
    #fetch-registry: true
    #register-with-eureka: true
    #enabled: true
    #service-url:
      #defaultZone: http://localhost:8761/eureka
    
      
