#spring:
  #application:
    #name: CONFIG-PROD
    
#eureka:
  #instance:
    #prefer-ip-address: true
  #client:
    #fetch-registry: true
    #register-with-eureka: true
    #enabled: true
    #service-url:
      #defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

#logging:
  #level:
    #root: INFO
    #org.springframework: INFO
    #org.hibernate.SQL: WARN
    #com.dev: DEBUG
  #pattern:
    #console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %c{1}:%L - %msg%n"
  #file:
    #name: logs/${spring.application.name}.log
  #logback:
    #rollingpolicy:
      #file-name-pattern: logs/${spring.application.name}-%d{yyyy-MM-dd}.log
      #max-file-size: 10MB
      #max-history: 10
  #charset:
    #console: UTF-8
    #file: UTF-8

#management:
  #server:
    #port: ${MANAGEMENT_PORT:${server.port}}
  #endpoints:
    #web:
      #exposure:
        #include: health,info,metrics,env,beans,loggers,threaddump,heapdump,refresh
      #base-path: /actuator
  #endpoint:
    #health:
      #show-details: always
    #loggers:
      #enabled: true
  #health:
    #livenessstate:
      #enabled: true
    #readinessstate:
      #enabled: true
  #info:
    #env:
      #enabled: true

#info:
  #app:
    #name: Hotel Management System
    #description: Microservices-based Hotel Booking Platform
    #version: 1.0.0
  #contact:
    #developer: Avinash Kumar
    #email: avinash@example.com
    #organization: MagadhSoft

 # Data Base credentials 
#DB_USERNAME:  {cipher}1636c31219daf406e5a14dd653347337a3f7b0cd4f7fb6c384454a126fac0119b257
#DB_PASSWORD:  {cipher}230000fbdc6c9dc8d47c82e1dfdb09dde4ecbab28263602f53e776331cee24d21b208

# Mailgun SMTP credentials 
#MAILGUN_USERNAME: {cipher}7266639b6419eb93f7c88ebf6d89ecd081a65b81de0b43cbd870bca32126eb5d12e1094ce6d803a105c29c3fbcfd4b83dae7655a9dff08a8e25e4d42401b06574ad2cc3d3c716194ab3b92490875e42ec4d2a
#MAILGUN_PASSWORD: {cipher}700003f3c316a12ff8da4e32cef75265b3b8d7f96f41673b3ee340a3e73a8e3ee042a7717eee084157eaf6cdb3c48cc910a238c919dbc19ba5426dc1af312f09836223a3d250ab2a9e3093f4ad7078e32307e

# Mailgun API credentials
#MAILGUN_API_KEY: {cipher}7000002405543b0d0b2f34445987dfad98d04cc00f8cca6ea0addd503bb8ac86b45c46987ebb2e1e7ebbe360d9733263710358fa475e9a27145aad59bb535a7548d32005b21f172f7c5bf84eb4f4874a7a06f
#MAILGUN_DOMAIN: {cipher}70333c5a524457d8353b720b1dd3e2e0d9a88732f73034f56b70c6de9aab581c612665a85d5eda75754eed01228d5b95c5f7c4eb082eed02629c1a6870bde9aab8a2a8238259c66a6cc89be62234364e02bb8

# Twilio SMS credentials
#TWILIO_ACCOUNT_SID: {cipher}54000942ccde1b93fe263f402322de07c53b0b35c4b0855ee4dbfa8c6dad32380d24f60b894614eb4343c8db7cf38fcb664f672fb8b9627469e538c1b439cd0d09f21
#TWILIO_AUTH_TOKEN: {cipher}5333371c6201afb16950b639d73d30570a8af29bf24e9ef1f1e6ce6479054374e29b985759e64a06a3856f86a0c2f09da787acb1b1d5e7586559db13035a0ccb55286
#TWILIO_FROM_PHONE: {cipher}256664e6e29f9ca2d26443c22f22e647b8db12e5c24dc9ab8ba51eecd28a007471c52

# ðŸ’³ PAYMENT GATEWAY CREDENTIALS (for PAYMENT-SERVICE)
#STRIPE_API_KEY: {cipher}118k8b76d680b65ccc9e5db58b2ba36150c525ec6d1fe48509a9bea1215cff51bd9f41a10834b0dd80cc7c48f0ad02db311f206ca818a38b5fdec06663e668dab3b852732bdfc14cee741e8e1c536507c5d5e2068339ae331c81dcf5024de2839a2a12c113c9789fb391f26cc0c638f9a9f33e7b39fd1848684b3b71a7cecf5fb78f
#STRIPE_WEBHOOK_SECRET: {cipher}553338529e1425ada348d8cf455c8cfe00c8b8187cefc97f26747e688569c56ebb8551c47440ca202b6408ae9a7d0f2b907449f82235110a86322cbb6d3f980e2c8e5
#RAZORPAY_KEY_ID: {cipher}39666e650247be53800b00161111927f3ea3a9d82672a7f914fb9bc471ed5f48cc72824a9a00585d3cfce8b80fd544d7b546b
#RAZORPAY_KEY_SECRET: {cipher}40000c8c26f320d7b252bb10d289614701d76eb8697890ccf273d957f9bb0ff53c870cb3493436dd7501a6d5be903a5da18ad

# COMMON SERVICE URLS
#MONGODB_URI: mongodb://localhost:27017/notification_service
#KAFKA_URL: localhost:9092
#EUREKA_URL: http://localhost:8761/eureka   
